# Subdomain-specific redirects - these must come FIRST
[[redirects]]
  from = "https://choreo.revolvo.tech/*"
  to = "https://revolvo.tech/:splat"
  status = 200
  force = true
  conditions = {Host = ["choreo.revolvo.tech"]}

[[redirects]]
  from = "https://admin.revolvo.tech/*"
  to = "https://revolvo.tech/:splat"
  status = 200
  force = true
  conditions = {Host = ["admin.revolvo.tech"]}

# Handle subdomain routing for all subdomains
[[redirects]]
  from = "https://*.revolvo.tech/*"
  to = "https://revolvo.tech/:splat"
  status = 200
  force = true

# Main domain SPA fallback (must come after subdomain rules)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# SEO-friendly redirects for common patterns
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/services"
  to = "/tech-showcase"
  status = 301

[[redirects]]
  from = "/portfolio"
  to = "/projects"
  status = 301

[build]
  command = "npm run build"
  publish = "dist"

# Enable advanced compression and optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Performance and SEO Security Headers for main domain
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app https://fonts.googleapis.com https://fonts.gstatic.com https://www.googletagmanager.com https://js.stripe.com https://m.stripe.com; connect-src 'self' blob: https://api.web3forms.com https://*.web3forms.com https://www.google-analytics.com https://*.google-analytics.com https://region1.google-analytics.com https://api.stripe.com https://m.stripe.com https://*.stripe.com; img-src 'self' data: blob: https: https://*.stripe.com; media-src 'self' blob: https:; font-src 'self' data: https: https://fonts.gstatic.com; frame-src 'self' https://calendly.com https://js.stripe.com https://hooks.stripe.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app https://assets.calendly.com https://www.googletagmanager.com https://js.stripe.com;"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance Headers
    X-DNS-Prefetch-Control = "on"
    
    # SEO Headers
    X-Robots-Tag = "index, follow"

# Subdomain-specific headers
[[headers]]
  for = "/*"
  [headers.values]
    # Allow subdomain access
    Access-Control-Allow-Origin = "https://choreo.revolvo.tech, https://admin.revolvo.tech, https://revolvo.tech"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
  condition = "Host"

# Cache optimization for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache for fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# HTML caching
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Robots-Tag = "index, follow"

# API routes caching
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Enhanced gzip compression
[build.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "20" 